/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.github.jonathanparra1013.gestionenvios.InterfazGraficaEnvio;
import com.github.jonathanparra1013.gestionenvios.*;
import java.util.*;
import javax.swing.JOptionPane;
/**
 *
 * @author jonap
 */
public class InterfazGraficEnvio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGraficEnvio.class.getName());
    ArrayList<Envio> listaEnvios = new ArrayList<>();
    /**
     * Creates new form InterfazGraficEnvio
     */
    public InterfazGraficEnvio() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tipos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtDestinatario = new javax.swing.JTextField();
        txtPeso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtHoraLimite = new javax.swing.JTextField();
        txtPaisDestino = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        lblHoraLimite = new javax.swing.JLabel();
        lblPaisDestino = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEnvios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Estandar", "Express", "Internacional" }));
        tipos.addActionListener(this::tiposActionPerformed);

        jLabel1.setText("Elija el Tipo de Envio que desea:");

        txtCodigo.addActionListener(this::txtCodigoActionPerformed);

        txtPeso.addActionListener(this::txtPesoActionPerformed);

        jLabel2.setText("Codigo");

        jLabel3.setText("Destinatario");

        jLabel4.setText("Peso");

        txtDireccion.addActionListener(this::txtDireccionActionPerformed);

        txtPaisDestino.addActionListener(this::txtPaisDestinoActionPerformed);

        lblDireccion.setText("Direccion");

        lblHoraLimite.setText("Hora Limite");

        lblPaisDestino.setText("Pais Destino");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        tablaEnvios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Destinatario", "Peso", "Tipo", "Valor a Pagar"
            }
        ));
        jScrollPane1.setViewportView(tablaEnvios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(btnRegistrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tipos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel2)))
                                .addGap(66, 66, 66)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(56, 56, 56)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59)
                                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblDireccion)
                                        .addGap(11, 11, 11)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHoraLimite)
                                    .addComponent(txtHoraLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPaisDestino)
                                    .addComponent(txtPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(lblDireccion)
                    .addComponent(lblHoraLimite)
                    .addComponent(lblPaisDestino))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaisDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnRegistrar)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        String codigo = txtCodigo.getText();
        String nombreDestinatario = txtDestinatario.getText();
        double peso = Double.parseDouble(txtPeso.getText());
        
        String modoEnvio = tipos.getSelectedItem().toString();
        Envio nuevoEnvio = null;
                
        if(modoEnvio == "Estandar"){
            String direccion = txtDireccion.getText();
            nuevoEnvio = new Estandar(direccion, codigo, nombreDestinatario, peso);
         
        }if(modoEnvio == "Express"){
            String hora_limite = txtHoraLimite.getText();
            nuevoEnvio = new Express(hora_limite, codigo, nombreDestinatario, peso);
            
        }if(modoEnvio == "Internacional"){
            String pais_destino = txtPaisDestino.getText();
            nuevoEnvio = new Internacional(pais_destino, codigo, nombreDestinatario, peso);
        }
        
        if(nuevoEnvio != null) {
            listaEnvios.add(nuevoEnvio);
           
            JOptionPane.showMessageDialog(this, "Envío registrado con éxito, Valor a pagar:" + nuevoEnvio.calcularCosto());
            
            actualizarTabla();
            this.vaciarCampos();
        }
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    
    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtPaisDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaisDestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaisDestinoActionPerformed

    private void tiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposActionPerformed
        String opcion = tipos.getSelectedItem().toString();
        if("Seleccione".equals(opcion)){
            txtDireccion.setVisible(false);
            lblDireccion.setVisible(false);
            
            txtPaisDestino.setVisible(false);
            lblPaisDestino.setVisible(false);
            
            txtHoraLimite.setVisible(false);
            lblHoraLimite.setVisible(false);
        }
        if(opcion == "Estandar"){
            txtDireccion.setVisible(true);
            lblDireccion.setVisible(true);
            
            txtPaisDestino.setVisible(false);
            lblPaisDestino.setVisible(false);
            
            txtHoraLimite.setVisible(false);
            lblHoraLimite.setVisible(false);
        }if(opcion == "Express"){
            txtDireccion.setVisible(false);
            lblDireccion.setVisible(false);
            
            txtPaisDestino.setVisible(false);
            lblPaisDestino.setVisible(false);
            
            txtHoraLimite.setVisible(true);
            lblHoraLimite.setVisible(true);
            
        }if(opcion == "Internacional"){
            txtDireccion.setVisible(false);
            lblDireccion.setVisible(false);
            
            txtPaisDestino.setVisible(true);
            lblPaisDestino.setVisible(true);
            
            txtHoraLimite.setVisible(false);
            lblHoraLimite.setVisible(false);
        }
    }//GEN-LAST:event_tiposActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed
    
    private void actualizarTabla() {
    String[] titulos = {"Codigo", "Destinatario", "Peso", "Tipo", "Valor a Pagar"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(null, titulos);
    
    for (Envio envio : listaEnvios) {
        String tipo = "";
        
        if (envio instanceof Estandar) {
            tipo = "Estandar";
        }if (envio instanceof Express) {
            tipo = "Express";
        }if (envio instanceof Internacional) {
            tipo = "Internacional";
        }

        Object[] fila = {
            envio.getCodigoEnvio(),envio.getNombreDestinatario(),envio.getPeso(),tipo,envio.calcularCosto()
        };

        modelo.addRow(fila);
    }

    tablaEnvios.setModel(modelo);
}
    
    private void vaciarCampos(){
        txtCodigo.setText("");
        txtDestinatario.setText("");
        txtPeso.setText("");
        txtDireccion.setText("");
        txtHoraLimite.setText("");
        txtPaisDestino.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazGraficEnvio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblHoraLimite;
    private javax.swing.JLabel lblPaisDestino;
    private javax.swing.JTable tablaEnvios;
    private javax.swing.JComboBox<String> tipos;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtHoraLimite;
    private javax.swing.JTextField txtPaisDestino;
    private javax.swing.JTextField txtPeso;
    // End of variables declaration//GEN-END:variables
}
